# Workflow that manually triggers a run of hi_rss_generator.py
name: Generate RSS feed

# Controls when the action will run
on:

  schedule:
    # Run every 12 hours (midnight and noon)
    - cron: "0 */12 * * *"

  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      output_file:
          description: "Name of the generated rss feed file"
          default: "rss.xml"
          required: false
      max_workers:
          description: "Max number of worker threads to use"
          default: 20
          type: number
          required: false
      first_episode_index:
          description: "Index of first episode to process (needs to map to valid episode url)"
          default: 1
          type: number
          required: false
      last_episode_index:
          description: "Index of last episode to process"
          default: 1000000
          type: number
          required: false

# Jobs part of this workflow
jobs:

  run:
    runs-on: ubuntu-latest

    # Set "global" environment variables (applicable to the whole job)
    env:
      PRODUCTION_RSS_XML: hi_archive_rss.xml

    steps:

      # Set up environment variables that default to the values given via "workflow_dispatch" inputs
      # (ie github.event.inputs.X), if available, otherwise the value from "env" is used.
      - name: Set variables
        env:
          PRODUCTION_RSS_XML: hi_archive_rss.xml
          DEFAULT_OUTPUT_FILE: rss.xml
          DEFAULT_MAX_WORKERS: 20
          DEFAULT_FIRST_EPISODE_INDEX: 1
          DEFAULT_LAST_EPISODE_INDEX: 1000000
        run: |
          echo "OUTPUT_FILE=${{github.event.inputs.output_file || env.DEFAULT_OUTPUT_FILE}}" >> $GITHUB_ENV
          echo "MAX_WORKERS=${{github.event.inputs.max_workers || env.DEFAULT_MAX_WORKERS}}" >> $GITHUB_ENV
          echo "FIRST_EPISODE_INDEX=${{github.event.inputs.first_episode_index || env.DEFAULT_FIRST_EPISODE_INDEX}}" >> $GITHUB_ENV
          echo "LAST_EPISODE_INDEX=${{github.event.inputs.last_episode_index || env.DEFAULT_LAST_EPISODE_INDEX}}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run hi_rss_generator.py
        run: "python3 hi_rss_generator.py \
              -o ${{env.OUTPUT_FILE}} \
              -m ${{env.MAX_WORKERS}} \
              -f ${{env.FIRST_EPISODE_INDEX}} \
              -l ${{env.LAST_EPISODE_INDEX}}"

      - name: Archive generated RSS feed
        uses: actions/upload-artifact@v3
        with:
          name: rss-feed
          path: ${{env.OUTPUT_FILE}}
          if-no-files-found: error

      # Uses parse_rss.py to read the xml file and transform it into a json file, which is then fed to "jq"
      # to extract the number of episodes present in file. We use an environment file to be able to keep
      # track of the resulting value across steps.
      # NOTE: We force "bash" shell to make sure any errors propagate correctly when piping commands.
      - name: Get number of new episodes
        id: new_episodes
        shell: bash
        run: |
          NUM_NEW_EPISODES=$(python3 parse_rss.py ${{env.OUTPUT_FILE}} | jq ". | length")
          echo "EPISODES=${NUM_NEW_EPISODES}" >> $GITHUB_OUTPUT

      # Uses parse_rss.py to read the xml file and transform it into a json file, which is then fed to "jq"
      # We use an environment file to be able to keep track of the resulting value across steps.
      # NOTE: We force "bash" shell to make sure any errors propagate correctly when piping commands.
      - name: Get number of existing episodes
        id: existing_episodes
        shell: bash
        run: |
          NUM_EXISTING_EPISODES=$(python3 parse_rss.py ${{env.PRODUCTION_RSS_XML}}  | jq ". | length")
          echo "EPISODES=${NUM_EXISTING_EPISODES}" >> $GITHUB_OUTPUT

      # Sends a Telegram message if new episodes are detected
      - name: New episodes detected alert
        uses: appleboy/telegram-action@master
        if: ${{ fromJSON(steps.new_episodes.outputs.EPISODES) > fromJSON(steps.existing_episodes.outputs.EPISODES) }}
        with:
          to: ${{secrets.TELEGRAM_CHAT_ID}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          message: "New episodes detected (${{steps.new_episodes.outputs.EPISODES}}) during
                   run #${{github.run_number}} of \"${{github.workflow}}\" workflow"
