# Workflow that manually triggers a run of hi_rss_generator.py
name: Run hi_rss_generator.py

# Controls when the action will run
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      out:
          description: "Name of the generated rss feed file"
          default: "rss.xml"
          required: false
      max_workers:
          description: "Max number of worker threads to use"
          default: "20"
          required: false
      first_episode_index:
          description: "Index of first episode to process (needs to map to valid episode url)"
          default: 1
          type: number
          required: false
      last_episode_index:
          default: 100000000
          description: "Index of last episode to process"
          type: number
          required: false

# Jobs part of this workflow
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run hi_rss_generator.py
      run: "python3 hi_rss_generator.py \
            -o ${{github.event.inputs.out}} \
            -m ${{github.event.inputs.max_workers}} \
            -f ${{github.event.inputs.first_episode_index}} \
            -l ${{github.event.inputs.last_episode_index}}"
    - name: Archive generated RSS feed
      uses: actions/upload-artifact@v2
      with:
        name: rss-feed
        path: ${{github.event.inputs.out}}
