# Workflow that manually triggers a run of hi_rss_generator.py

name: Run hi_rss_generator.py

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      out:
          description: "Name of the generated rss feed file"
          default: "rss.xml"
          required: false
      max_workers:
          description: "Max number of worker threads to use"
          default: "20"
          required: false
      first_episode_index:
          description: "Index of first episode to process (needs to map to valid episode url)"
          default: 1
          type: number
          required: false
      last_episode_index:
          default: 100000000
          description: "Index of last episode to process (needs to map to valid episode url)"
          type: number
          required: false

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run hi_rss_generator.py
      run: python3 "hi_rss_generator.py -o ${{github.event.inputs.out}} -m ${{github.event.inputs.max_workers}} -f ${{github.event.inputs.first_episode_index}} -l ${{github.event.inputs.last_episode_index}}"
