# Workflow that manually triggers a run of hi_rss_generator.py
name: Run hi_rss_generator.py

# Controls when the action will run
on:

  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"

  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      output_file:
          description: "Name of the generated rss feed file"
          default: "rss.xml"
          required: false
      max_workers:
          description: "Max number of worker threads to use"
          default: 20
          type: number
          required: false
      first_episode_index:
          description: "Index of first episode to process (needs to map to valid episode url)"
          default: 1
          type: number
          required: false
      last_episode_index:
          description: "Index of last episode to process"
          default: 100000000
          type: number
          required: false

# Jobs part of this workflow
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        env:
          DEFAULT_OUTPUT_FILE: rss.xml
          DEFAULT_MAX_WORKERS: 20
          DEFAULT_FIRST_EPISODE_INDEX: 1
          DEFAULT_LAST_EPISODE_INDEX: 100000000
        run: |
          echo "OUTPUT_FILE = ${{ github.event.inputs.output_file || env.DEFAULT_OUTPUT_FILE }}" >> $GITHUB_ENV
          echo "MAX_WORKERS = ${{ github.event.inputs.max_workers || env.DEFAULT_MAX_WORKERS }}" >> $GITHUB_ENV
          echo "FIRST_EPISODE_INDEX = ${{ github.event.inputs.first_episode_index || env.DEFAULT_FIRST_EPISODE_INDEX }}" >> $GITHUB_ENV
          echo "LAST_EPISODE_INDEX = ${{ github.event.inputs.last_episode_index || env.DEFAULT_LAST_EPISODE_INDEX }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run hi_rss_generator.py
        run: "python3 hi_rss_generator.py \
              -o $OUTPUT_FILE \
              -m $MAX_WORKERS \
              -f $FIRST_EPISODE_INDEX \
              -l $LAST_EPISODE_INDEX"
      - name: Archive generated RSS feed
        uses: actions/upload-artifact@v2
        with:
          name: rss-feed
          path: ${{github.event.inputs.out}}
