# Workflow that send a message via Telegram using the @hello_internet_rss_generator_bot
name: Send Telegram message

# Controls when the action will run
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      message:
          description: "Message"
          required: true

# Jobs part of this workflow
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{github.event.inputs.message}}
