# Workflow that manually triggers a run of hi_rss_generator.py
name: Run tests

# Controls when the action will run
on:

  workflow_dispatch:

# Jobs part of this workflow
jobs:

  run:
    runs-on: ubuntu-latest

    steps:

      # Set environment variables that default to the ones provided via "workflow_dispatch" inputs,
      # (ie "github.event.inputs.X") if available.
      - name: Set variables
        env:
          DEFAULT_OUTPUT_FILE: hi_archive_rss.xml
          DEFAULT_MAX_WORKERS: 20
          DEFAULT_FIRST_EPISODE_INDEX: 1
          DEFAULT_LAST_EPISODE_INDEX: 100000000
        run: |
          echo "OUTPUT_FILE=${{ github.event.inputs.output_file || env.DEFAULT_OUTPUT_FILE }}" >> $GITHUB_ENV
          echo "MAX_WORKERS=${{ github.event.inputs.max_workers || env.DEFAULT_MAX_WORKERS }}" >> $GITHUB_ENV
          echo "FIRST_EPISODE_INDEX=${{ github.event.inputs.first_episode_index || env.DEFAULT_FIRST_EPISODE_INDEX }}" >> $GITHUB_ENV
          echo "LAST_EPISODE_INDEX=${{ github.event.inputs.last_episode_index || env.DEFAULT_LAST_EPISODE_INDEX }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get number of episodes processed
        run: |
          echo ::set-output name=EPISODES::$(python3 parse_rss.py ${{ env.OUTPUT_FILE }})
        id: current_episodes

      - name: Print episodes processed
        run: |
          echo Episodes preocessed: ${{ steps.current_episodes.outputs.EPISODES }}
